# Generated by Django 3.2.5 on 2021-07-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_updated",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Last updated"
            ),
        ),
    ]
