"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 3.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
from pathlib import Path

from decouple import config
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration

from .logging import CONFIG as LOG_CONFIG

ENVIRON = config('ENVIRON', default='prod')

sentry_sdk.init(
    dsn=f"https://ad9a9f987fa949a899c3b890ef4cd112"
        f"@o354850.ingest.sentry.io/5868398",
    integrations=[DjangoIntegration()],
    environment=ENVIRON,
    traces_sample_rate=1.0,
    send_default_pii=True,
    release="tda@0.1.0",  # change in poetry as well
)

LOGGING = LOG_CONFIG

PROJECT_NAME = 'The Doe Agency'
PROJECT_SLUG = 'the-doe-agency'
PROJECT_CODE = 'TDA'

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default=[], cast=list)


# Application definition ---------------------------------------------------- #

INSTALLED_APPS = [
    # django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 3rd party apps
    # ...
    # project apps
    # ...
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database ------------------------------------------------------------------ #
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': config('DB_ENGINE', default='django.db.backends.postgresql'),
        'HOST': config('DB_HOST', default='127.0.0.1'),
        'PORT': config('DB_PORT', default=5432, cast=int),
        'NAME': config('DB_NAME', default='tda_db'),
        'USER': config('DB_USER', default='tda_user'),
        'PASSWORD': config('DB_PASS', default='tda_pass')
    }
}


# Password validation ------------------------------------------------------- #
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': f'django.contrib.auth.password_validation'
             f'.UserAttributeSimilarityValidator'},
    {'NAME': f'django.contrib.auth.password_validation'
             f'.MinimumLengthValidator'},
    {'NAME': f'django.contrib.auth.password_validation'
             f'.CommonPasswordValidator'},
    {'NAME': f'django.contrib.auth.password_validation'
             f'.NumericPasswordValidator'},
]


# Internationalization ------------------------------------------------------ #
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = config('TIME_ZONE', default='UTC')

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images) ------------------------------------ #
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
