# Generated by Django 3.2.5 on 2021-07-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0002_auto_20210719_1549"),
    ]

    operations = [
        migrations.CreateModel(
            name="Scrape",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Active Status"
                    ),
                ),
                (
                    "proxies",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Proxies scraped"
                    ),
                ),
                (
                    "error",
                    models.TextField(
                        blank=True, null=True, verbose_name="Error message"
                    ),
                ),
                (
                    "is_success",
                    models.BooleanField(
                        default=False, verbose_name="Success status"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Datetime of Completion",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-completed_at"),
            },
        ),
        migrations.AlterModelOptions(
            name="proxy",
            options={"ordering": ("-id",), "verbose_name_plural": "Proxies"},
        ),
        migrations.AddIndex(
            model_name="proxy",
            index=models.Index(
                fields=["-created_at"], name="scraper_pro_created_00ffc1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="proxy",
            index=models.Index(
                fields=["-checked_at"], name="scraper_pro_checked_9ec19e_idx"
            ),
        ),
        migrations.AddField(
            model_name="scrape",
            name="pages",
            field=models.ManyToManyField(
                related_name="pages", to="scraper.Page"
            ),
        ),
        migrations.AddField(
            model_name="scrape",
            name="sites",
            field=models.ManyToManyField(
                related_name="sites", to="scraper.Website"
            ),
        ),
        migrations.AddIndex(
            model_name="scrape",
            index=models.Index(
                fields=["id"], name="scraper_scr_id_83abcf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scrape",
            index=models.Index(
                fields=["-id"], name="scraper_scr_id_34e0a2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scrape",
            index=models.Index(
                fields=["-created_at"], name="scraper_scr_created_0100ab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scrape",
            index=models.Index(
                fields=["-completed_at"], name="scraper_scr_complet_89a055_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scrape",
            index=models.Index(
                fields=["-created_at", "-completed_at"],
                name="scraper_scr_created_7018a1_idx",
            ),
        ),
    ]
